Editorial: Add note on ignored argument of Symbol.prototype[@@toPrimitive]
tc39/ecma262 pull request #2160
Opened 2020-08-30 06:23 UTC by shvaikalesh

Aligns it with [`Date.prototype.toJSON`](https://tc39.es/ecma262/#sec-date.prototype.tojson) and removes incorrect "allowed values" note.

2020-08-31 14:55 UTC, ExE-Boss commented
The specification of the `%Symbol.toPrimitive%` well‑known symbol is that the <code><var>hint</var></code> parameter is expected to be one of `"default"`, `"number"`, or `"string"`.

2020-08-31 16:00 UTC, bathos commented
@ExE-Boss It appears that `Symbol.prototype[Symbol.toPrimitive]` is already specced to ignore the hint arg entirely, unlike `Date.prototype[Symbol.toPrimitive]` (which throws if it’s not given a valid hint), so I think this editorial update is removing misleading noise.

2020-08-31 17:41 UTC, ljharb commented
It kind of seems like there should be a normative PR to make `Symbol.prototype[Symbol.toPrimitive]` throw when it receives an invalid hint - iow, the runtime exception is the bug, not the redundant note?

2020-09-02 23:38 UTC, michaelficarra approved these changes

2020-09-03 22:39 UTC, ljharb approved these changes
Since it's unlikely there will be an appetite for a normative change here (either making a bad hint throw, or, removing the hint arg entirely and changing the length), this is fine.

2020-09-04 17:39 UTC, shvaikalesh commented
I'm up for submitting a normative PR + tests + JSC patch for throwing on a bad hint, but it might not be web-compatible if there is code like `symbol[Symbol.toPrimitive]()`.

> removing the hint arg entirely and changing the length

Isn't having the `"length"` of `1` while ignoring the argument prevents implementors from extending this method? Pretty much like `Object.prototype.toLocaleString ( [ reserved1 [ , reserved2 ] ] )`.

2020-09-04 17:51 UTC, bakkot commented
I'd prefer not to change the behavior. I don't think there's much user benefit to throwing; certainly not enough to justify the runtime overhead and web-compat risk.

2020-09-11 17:23 UTC, ExE-Boss commented
> I'm up for submitting a normative PR + tests + JSC patch for throwing on a bad hint, but it might not be web-compatible if there is code like `symbol[Symbol.toPrimitive]()`.

We could make that specific case behave the same as `hint === "default"`.

2020-09-11 21:13 UTC, ljharb commented
At that point we'd lack the consistency angle :-/

2020-09-12 23:01 UTC, bakkot approved these changes

2020-09-13 04:07 UTC, dabonneur requested changes
![Uploading 93009981...]

2020-09-13 04:07 UTC, dabonneur commented
> ![Uploading 93009981...]

2020-09-13 04:15 UTC, dabonneur commented
stop please

2020-09-13 04:16 UTC, dabonneur requested changes
![image](https://user-images.githubusercontent.com/71188147/93009981-adc65f80-f54c-11ea-8756-f58ec5317aa4.jpeg)

2020-09-13 04:16 UTC, dabonneur requested changes
jjb

2020-09-13 04:16 UTC, dabonneur requested changes
[](https://github.com/tc39/ecma262/pull/2160)

2020-09-13 04:16 UTC, dabonneur commented
####-

2020-09-13 04:17 UTC, dabonneur requested changes
ok

2020-09-13 04:17 UTC, dabonneur requested changes
-

2020-09-13 04:25 UTC, dabonneur approved these changes

2020-09-13 04:25 UTC, dabonneur commented on spec.html
>        </emu-clause>
an[](https://github.com/tc39/ecma262/pull/2160)

2020-09-13 20:27 UTC, merged