Editorial: add missing assertion to ApplyStringOrNumericBinaryOperator
tc39/ecma262 pull request #2282
Opened 2021-01-18 21:43 UTC by ljharb

Fixes #2281

2021-01-19 17:12 UTC, michaelficarra approved these changes

2021-01-19 20:57 UTC, jmdyck requested changes
Why move the table out of the algorithm? In the context of the algorithm, the aliases `_opText_`, `_operation_`, and `_T_` all have meaning. Outside the algorithm, they don't.

If the point is just to be able to refer to the table from the Assertion, you don't need to make it a 'free-standing' table, you could just give step 8 an `[id="..."]` and say:
`Assert: _opText_ is present in the table in [step 8].`

2021-01-19 20:57 UTC, jmdyck commented on spec.html
> +      <emu-table id="table-applystringornumericbinaryoperator-operations">
This table has no caption.

2021-01-19 20:57 UTC, jmdyck commented on spec.html
> +        <table class="lightweigt-table">
```suggestion
        <table class="lightweight-table">
```

2021-01-19 21:08 UTC, ljharb commented
@jmdyck because it wouldn't render properly with an ID when it's inside the algorithm - i didn't think of using step IDs tho, i'll try that.

2021-01-19 21:18 UTC, ljharb commented
Updated to use a step xref instead of altering the table.

2021-01-19 21:58 UTC, michaelficarra commented
I kinda preferred moving the table out. We could use better column headers if the variable names would be confusing there.

2021-01-19 22:03 UTC, ljharb commented
cool, let's figure it out tomorrow on the call; i can easily revert back.

2021-01-20 19:04 UTC, jmdyck commented
> I kinda preferred moving the table out. We could use better column headers if the variable names would be confusing there.

Yeah, but it's unclear what you'd do about the references to `_T_`.

2021-01-20 19:17 UTC, jmdyck approved these changes
I mean, I'm not convinced of the need (usefulness) of this assertion, but I recognize that that's a matter of taste; and if you want an assertion, this (with the table embedded in the algorithm) seems like the easiest (least problematic) way to achieve that.

2021-01-20 22:44 UTC, bakkot approved these changes
Inline LGTM.

2021-01-20 22:44 UTC, syg approved these changes

2021-01-20 22:45 UTC, merged