fix: Remove percent sign from IDs
tc39/ecma262 pull request #2299
Opened 2021-02-08 21:39 UTC by nschonni

2021-02-08 21:46 UTC, devsnek commented
If these are changed, they need `oldid` entries (`<x oldids="oldid1,oldid2,etc">`). That being said, I don't think they should be changed, they're totally valid ids.

2021-02-08 21:51 UTC, bakkot commented
> they need `oldid` entries

And doing so will cause elements with `%` to be generated anyway, so there's no way to eliminate them without breaking links.

---

In any case, what's wrong with `%`? The HTML spec [says](https://html.spec.whatwg.org/multipage/dom.html#global-attributes)

> the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character. The value must not contain any ASCII whitespace. [...] There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

2021-02-08 21:56 UTC, nschonni commented
You're right that it isn't a restricted character anymore in HTML5, but `%` has meaning in the end URL which these are used as the anchors.
Realized I also didn't hit all the instances with a quick find/replace regex as well

2021-02-08 22:04 UTC, jmdyck requested changes

2021-02-08 22:04 UTC, jmdyck commented on spec.html
> +      <emu-clause id="sec-typedarray">
Collides with existing id.

2021-02-08 22:04 UTC, jmdyck commented on spec.html
> +      <emu-clause id="sec-typedarray.prototype">
Collides with existing id.

2021-02-08 22:04 UTC, jmdyck commented on spec.html
> +      <emu-clause id="sec-typedarray.prototype.constructor">
Collides with existing id.

2021-02-08 23:51 UTC, ljharb commented
@nschonni what meaning does it have?

2021-02-09 00:07 UTC, nschonni commented
The beginning of a percent encoded bytes https://url.spec.whatwg.org/#percent-encoded-bytes
Although I think none of the find/replaced ones sequential HEX characters

2021-02-09 00:11 UTC, ljharb commented
@nschonni has that always been the case? or did adding that feature break the web, at least the part of the web that's using %'s in anchors, like this part?

2021-02-09 00:14 UTC, bakkot commented
@ljharb Percent-encoding in URLs has been a thing for a very long time.

2021-02-09 00:17 UTC, ljharb commented
ah, true. but the URLs that we use, with the `%`, have worked for a long time as well. What's the impetus to change them now?

2021-02-09 01:44 UTC, devsnek commented
> And doing so will cause elements with % to be generated anyway; there's no way to eliminate %s in ids in the generated document without breaking links.

@bakkot my understanding is that this PR is here to enable the links in webidl to pass some sort of html validator, not emca262 itself (which one is yet unclear, like as you and i said above, the ids are valid)

2021-02-09 06:18 UTC, mathiasbynens commented
Based on the description in https://github.com/heycam/webidl/pull/955, @nschonni is trying to address an *upstream* HTML validation issue. I’m guessing it’s the following:

```html
<a href="https://tc39.es/ecma262/#sec-%typedarray%-intrinsic-object">foo</a>
```

> Error: Bad value `https://tc39.es/ecma262/#sec-%typedarray%-intrinsic-object` for attribute `href` on element `a`: Percentage ("%") is not followed by two hexadecimal digits.

That said, if upstream HTML validation is the goal, then rather than making changes to ECMA-262, the upstream HTML document should be patched (e.g. by URL-encoding the `%` sign as `%25` in the above HTML snippet).

2021-02-17 22:50 UTC, bakkot commented
Closing in light of @mathiasbynens's comment.

2021-02-17 22:50 UTC, closed without merging