Editorial: have CreateIteratorFromClosure provide a new execution context to GeneratorStart
tc39/ecma262 pull request #2398
Opened 2021-04-29 05:08 UTC by bakkot

See more complete discussion in https://es.discourse.group/t/execution-context-suspension-and-resumption/756. I'll summarize:

[GeneratorStart](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorstart) manipulates the code evaluation state of the running execution context, and also stores that context on the generator object. Prior to https://github.com/tc39/ecma262/pull/2045, the sole caller of GeneratorStart was in [EvaluateGeneratorBody](https://tc39.es/ecma262/multipage/#sec-runtime-semantics-evaluategeneratorbody) (although it wasn't called that at the time). So, in particular, GeneratorStart was only invoked in step 7 of [[[Call]] for ordinary functions](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ecmascript-function-objects-call-thisargument-argumentslist), at which time the running execution context would have been one created specifically for the evaluation of the generator in step 3 of [[Call]] - that is, the execution state being manipulated and stored would have been created specifically for the generator.

But https://github.com/tc39/ecma262/pull/2045 introduced a new callsite, [CreateIteratorFromClosure](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-createiteratorfromclosure). Here the execution context is not created for the "generator"; it's just whatever happens to be running at the time.

The fix, I believe, is to have CreateIteratorFromClosure create a push a new context before calling GeneratorStart, and pop it after. That way it can "belong" to the synthetic generator it's creating. That is what this PR does.

2021-04-29 14:45 UTC, jmdyck requested changes

2021-04-29 14:45 UTC, jmdyck commented on spec.html
> +          1. Set the Realm of _calleeContext_ to the current Realm record.
```suggestion
          1. Set the Realm of _calleeContext_ to the current Realm Record.
```

2021-04-29 14:45 UTC, jmdyck commented on spec.html
> +          1. Set the ScriptOrModule of _calleeContext_ to to _callerContext_'s ScriptOrModule.
```suggestion
          1. Set the ScriptOrModule of _calleeContext_ to _callerContext_'s ScriptOrModule.
```

2021-04-30 21:21 UTC, bakkot commented
I suppose an alternative is to have GeneratorStart create an execution context itself, and never push it to the execution context stack. That has the advantage that it would not be manipulating the code evaluation state of the running execution context, but the disadvantage that there would then be two execution contexts created for a generator: one for evaluating the parameters, created by [[Call]], and one for evaluating the body, created by GeneratorStart.

2021-06-09 22:16 UTC, syg approved these changes

2021-06-11 17:28 UTC, michaelficarra approved these changes

2021-07-07 23:45 UTC, merged