Editorial (?): Clarify the AsyncGenerator state machine
tc39/ecma262 pull request #2413
Opened 2021-05-24 07:00 UTC by bakkot

AsyncGenerators are complicated, but at the root there's a relatively straightforward state machine. I find that it's difficult to see the shape of that machine with the current spec text, which routes every operation through [AsyncGeneratorResumeNext](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-asyncgeneratorresumenext).

I've rewritten all the logic here. The main reason I prefer this text is that each AO does one thing and returns, instead of kicking off a chain of self-recursive AOs which you have to follow for quite a while, keeping track of the state, before you figure out what's actually going to happen. For example, I think this PR makes it much more obvious that AsyncGeneratorYield might not return control to the rest of the program, and under what circumstances that happens. As a bonus, it makes AsyncGeneratorYield follow the pattern described in [this comment](https://github.com/tc39/ecma262/issues/2400#issuecomment-832335872), hopefully providing a path towards [clarifying execution context juggling](https://github.com/tc39/ecma262/issues/2409).

I don't believe there's any normative changes except for possibly, in certain cases, to the realm used for creating iterator result objects.

This PR has an incorrect `!` assertion in callers of AsyncGeneratorAwaitReturn, corresponding to the same assertion in callers of AsyncGeneratorResumeNext described in https://github.com/tc39/ecma262/issues/2412. I'll fix this PR up if that issue is resolved first. Otherwise it just leaves things in the same state.

Rather than trying to confirm that the logic is the same by comparing the two texts, I strongly suggest you read [this gist](https://gist.github.com/bakkot/82186e27a2e78c6e507c56dd49d8a197) where I've described the state machine, and confirm that both the original spec text and the text in this PR correspond to that state machine.

cc @jmdyck, I know you've spent a long time puzzling over this as well.

2021-05-25 15:17 UTC, jmdyck requested changes

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +            1. Return _promiseCapability_.
A function can't return a spec Record.

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +        <p>The abstract operation AsyncGeneratorEnqueue takes arguments _generator_ (an Async Generator), _completion_ (a Completion Record), and _promiseCapability_ (a PromiseCapability Record). It
```suggestion
        <p>The abstract operation AsyncGeneratorEnqueue takes arguments _generator_ (an AsyncGenerator), _completion_ (a Completion Record), and _promiseCapability_ (a PromiseCapability Record). It performs the following steps when called:</p>
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +          1. Let _realm_ be the current Realm record.
```suggestion
          1. Let _realm_ be the current Realm Record.
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +      <emu-clause id="sec-ascyngeneratorcompletestep" aoid="AsyncGeneratorCompleteStep">
```suggestion
      <emu-clause id="sec-asyncgeneratorcompletestep" aoid="AsyncGeneratorCompleteStep">
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +        <p>The abstract operation AsyncGeneratorCompleteStep takes arguments _generator_ (an AsyncGenerator) and _completion_ (a Completion Record). It performs the following steps when called:</p>
```suggestion
        <p>The abstract operation AsyncGeneratorCompleteStep takes arguments _generator_ (an AsyncGenerator), _completion_ (a Completion Record), and _done_ (a Boolean). It performs the following steps when called:</p>
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +          1. Let _completion_ be NormalCompletion(value).
```suggestion
          1. Let _completion_ be NormalCompletion(_value_).
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +          1. Let _next_ the first element of _queue_.
```suggestion
          1. Let _next_ be the first element of _queue_.
```

2021-05-25 15:17 UTC, jmdyck commented on spec.html
> +              1. If _queue_ is empty, set *done* to *true*.
```suggestion
              1. If _queue_ is empty, set _done_ to *true*.
```

2021-05-25 15:18 UTC, jmdyck commented
Also, this PR undefines the following ids:
- sec-asyncgeneratorreject
- sec-asyncgeneratorresolve
- sec-asyncgeneratorresumenext

(I don't know if there's an appropriate place to make them oldids.)

2021-06-05 17:13 UTC, bakkot commented on spec.html
> +            1. Return _promiseCapability_.
Fixed.

2021-06-05 17:16 UTC, bakkot commented
> Also, this PR undefines the following ids:

Yeah, I don't think there's a reasonable place to put them. They don't really correspond to any of the new operations - the whole point of the PR is that those previous operations were not a clean way of organizing the logic here, after all.

2021-06-07 14:05 UTC, jmdyck commented on spec.html
> +          1. Let _previousContext_ be the execution context immediately beneath the running execution context.
```suggestion
          1. Assert: The execution context stack has at least two elements.
          1. Let _previousContext_ be the second to top element of the execution context stack.
```
(precedent in [19.2.1 eval(x)](https://tc39.es/ecma262/#sec-eval-x) and [20.2.1.1.1 CreateDynamicFunction](https://tc39.es/ecma262/#sec-createdynamicfunction))

2021-06-10 00:28 UTC, syg approved these changes
@michaelficarra and I are splitting up reviewing the current text for correspondence with [the gist](https://gist.github.com/bakkot/82186e27a2e78c6e507c56dd49d8a197) and reviewing the PR text for correspondence.

This lgtm is for correspondence with the current text.

The state machine in the gist reads correct to me. My understanding is as follows.

The current spec uses AsyncGeneratorResumeNext as a message pump that ~~blocks~~ suspends to wait for new messages. That is, it doesn't just resume next and continues execution, it generally pumps until it runs out of messages. This pump loop is awkwardly captured by self-recursive calls in the following states:

- From `executing`, when a `yield` is evaluated, if the queue is not empty, there is a synchronous transition `executing` -> `suspendedYield` -> `executing`.
- From `completed`, the queue is pumped and each promise is resolved with undefined until a return completion, in which case it goes into `awaiting-return`.

Put a third way, the current spec puts the focus on the message pump machinery, which is more confusing than putting the focus on the state machine machinery.

2021-06-15 22:07 UTC, michaelficarra commented on spec.html
> +          <h1>AsyncGeneratorAwaitReturn Fulfilled Functions</h1>
I'd prefer to finish up #2109 and then make these abstract closures.

2021-06-15 22:07 UTC, michaelficarra commented on spec.html
> +          <p>An AsyncGeneratorAwaitReturn fulfilled function is an anonymous built-in function that is used as part of the AsyncGeneratorAwaitReturn specification device to unwrap promises passed in
```suggestion
          <p>An AsyncGeneratorAwaitReturn fulfilled function is an anonymous built-in function that is used as part of the AsyncGeneratorAwaitReturn specification device to unwrap promises passed in to the <emu-xref href="#sec-asyncgenerator-prototype-return" title></emu-xref> method. Each AsyncGeneratorAwaitReturn fulfilled function has a [[Generator]] internal slot.</p>
```

2021-06-15 22:09 UTC, michaelficarra approved these changes
LGTM with respect to correspondence to the state machine.

2021-07-07 23:50 UTC, merged