Meta: Upgrade ESMeta to v0.3.1
tc39/ecma262 pull request #3078
Opened 2023-05-27 13:56 UTC by jhnaldo

I updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [`v0.3.1`](https://github.com/es-meta/esmeta/releases/tag/v0.3.1).

We fixed the bug in the grammar parser related to https://github.com/es-meta/esmeta/issues/145 and https://github.com/tc39/ecma262/pull/2418#discussion_r1173563802.

2023-05-30 06:27 UTC, mathiasbynens commented
This would make the PR checks on #2418 green!

2023-05-30 16:14 UTC, michaelficarra requested changes
I want to wait on response to this: https://github.com/es-meta/esmeta/pull/146#pullrequestreview-1451151342

2023-05-31 15:25 UTC, michaelficarra approved these changes

2023-05-31 21:32 UTC, bakkot approved these changes

2023-05-31 21:40 UTC, merged