Editorial: Add %GeneratorPrototype% and %AsyncGeneratorPrototype% well-known intrinsics (#3230)
tc39/ecma262 pull request #3238
Opened 2023-12-05 23:58 UTC by arai-a

This supersedes https://github.com/tc39/ecma262/pull/3234

This is effectively same as https://github.com/tc39/ecma262/pull/3234, but in order to avoid the readability issue, added dedicate well-known intrinsics for Generator prototype and Async generator prototype, that's used in the same way as %SetIteratorPrototype%.

  * All occurrences of "Generator Prototype" and "Generator.prototype" are replaced with %GeneratorPrototype%
  * All occurrences of "AsyncGenerator Prototype" and "AsyncGenerator.prototype" are replaced with %AsyncGeneratorPrototype%
  * Related ids are updated, with moving the old ids into `oldids` attribute
  * Also tweaked the description of Generator and AsyncGenerator to avoid the confusion from "instance of"+"generator function"

2023-12-06 00:00 UTC, ljharb commented
We generally are trying not to add any more top-level intrinsics, but I agree this might improve readability.

2023-12-08 21:24 UTC, michaelficarra commented
This will also have to update figure 6: https://tc39.es/ecma262/#figure-2

2023-12-08 21:51 UTC, arai-a commented
> This will also have to update figure 6: https://tc39.es/ecma262/#figure-2

Just to make sure, it's is the following parts, right?
  * `%GeneratorFunction.prototype.prototype%` in the green box at the middle-right
    * technically this is still correct, but adding `%GeneratorPrototype%` in the box can make it clearer
  * "... to its generator function's instances" in the pink box at the bottom-center
    * replace with "... to generators created by calling its generator function", for clarity

The following seems to be slightly unclear, but it matches to other parts:
  * "abstract constructor of Generator instances" in the pink box at the middle-center
    * "Generator" and "Generator instances" are used in the same meaning.  [Generator Objects](https://tc39.es/ecma262/#sec-generator-objects)'s 2nd paragraph also mentions "Generator instances"
    * maybe replace with "abstract constructor of generators" ?

Then, there seems to be no SVG file.
I'm happy to create a new one if necessary.

2023-12-08 22:01 UTC, ljharb commented
i'm not sure when it was ever an svg; i just edit the png locally when i make changes to it.

2023-12-08 22:01 UTC, michaelficarra commented
@arai-a The source for that image is at https://github.com/tc39/ecma262/blob/main/figure-2.uxf

2023-12-08 22:23 UTC, jmdyck requested changes

2023-12-08 22:23 UTC, jmdyck commented on spec.html
> +        <li>is the initial value of <dfn>%GeneratorFunction.prototype.prototype%</dfn>.</li>
```suggestion
        <li>is <dfn>%GeneratorFunction.prototype.prototype%</dfn>.</li>
```
You can talk about the initial value of an intrinsic object's property (or internal slot), but it doesn't make sense to talk about the initial value of an intrinsic object itself.

2023-12-08 22:23 UTC, jmdyck commented on spec.html
> +        <li>is the initial value of <dfn>%AsyncGeneratorFunction.prototype.prototype%</dfn>.</li>
```suggestion
        <li>is <dfn>%AsyncGeneratorFunction.prototype.prototype%</dfn>.</li>
```
Ditto.

2023-12-08 23:48 UTC, arai-a commented
I tried modifying the `figure-2.uxf` file, but that format doesn't seem to preserve the font face across environments,
and I cannot generate an equivalent PNG file.

I use UMLet 15.1 downloaded from https://www.umlet.com/index.html on Linux (Ubuntu).
The font it's using on my environment seems to be different than the current PNG file's one, and the text overflows from the box.
I can modify the box size and line wrapping to make it "good" on my environment, and then generate PNG file, but the uxf file won't look good on other environments.

What should I do?
I'm leaning toward replacing it with SVG, that's more portable...

2023-12-09 00:23 UTC, michaelficarra commented
Replacing it with an SVG is also fine. If you do, please do so as a separate PR.

2024-01-12 12:35 UTC, arai-a commented
Updated the SVG figure, replacing `%GeneratorFunction.prototype.prototype%` with `%GeneratorPrototype%`, and also tweaking the layout to make it centered again (it's shifted by https://github.com/tc39/ecma262/pull/3239 to make the content fit)

2024-01-13 00:54 UTC, michaelficarra commented on spec.html
>                  The constructor of async iterator objects (<emu-xref href="#sec-asyncgeneratorfunction-constructor"></emu-xref>)
This description should match the description you've used for `%GeneratorFunction%`.

2024-01-13 00:58 UTC, michaelficarra approved these changes
I think the new section IDs are mostly unnecessary and just bloat the document with oldids. Otherwise LGTM.

2024-01-13 07:23 UTC, arai-a commented
reverted ids, and updated `%AsyncGeneratorFunction%` description

2024-01-28 01:16 UTC, jmdyck reviewed
Looks okay to me.

2024-01-31 08:15 UTC, arai-a commented
I'm not sure what happened, but "1 change requested" is still there.
I don't see any unresolved comment.

2024-01-31 14:33 UTC, jmdyck approved these changes

2024-01-31 14:42 UTC, jmdyck commented
Apparently, resolving all comments doesn't make "1 change requested" go away. Instead, the change-requesting review must be either dismissed or replaced with an approval.

2024-02-21 22:56 UTC, bakkot approved these changes

2024-02-21 22:57 UTC, michaelficarra commented on spec.html
> +    <p>Generator instances directly inherit properties from the object that is the initial value of the *"prototype"* property of the generator function that created the instance. Generator instances
```suggestion
    <p>Generator instances directly inherit properties from the initial value of the *"prototype"* property of the generator function that created the instance. Generator instances indirectly inherit properties from %GeneratorPrototype%.</p>
```

2024-02-21 22:58 UTC, michaelficarra commented on spec.html
> +    <p>AsyncGenerator instances directly inherit properties from the object that is the initial value of the *"prototype"* property of the async generator function that created the instance. AsyncGen
```suggestion
    <p>AsyncGenerator instances directly inherit properties from the initial value of the *"prototype"* property of the async generator function that created the instance. AsyncGenerator instances indirectly inherit properties from %AsyncGeneratorPrototype%.</p>
```

2024-02-21 22:59 UTC, syg approved these changes

2024-02-21 22:59 UTC, syg commented on spec.html
> +    <p>Generator instances directly inherit properties from the object that is the initial value of the *"prototype"* property of the generator function that created the instance. Generator instances
```suggestion
    <p>Generator instances directly inherit properties from the initial value of the *"prototype"* property of the generator function that created the instance. Generator instances indirectly inherit properties from %GeneratorPrototype%.</p>
```

2024-02-21 22:59 UTC, syg commented on spec.html
> +    <p>AsyncGenerator instances directly inherit properties from the object that is the initial value of the *"prototype"* property of the async generator function that created the instance. AsyncGen
```suggestion
    <p>AsyncGenerator instances directly inherit properties from the initial value of the *"prototype"* property of the async generator function that created the instance. AsyncGenerator instances indirectly inherit properties from %AsyncGeneratorPrototype%.</p>
```

2024-02-21 23:15 UTC, merged