Markup: fix SAB toStringTag section ID
tc39/ecma262 pull request #3285
Opened 2024-02-19 20:34 UTC by ljharb

Fixes #3284

2024-02-19 20:35 UTC, linusg requested changes

2024-02-19 20:35 UTC, linusg commented on spec.html
> +      <emu-clause oldids="sec-sharedarraybuffer.prototype.toString" id="https://tc39.es/ecma262/#sec-sharedarraybuffer.prototype-@@tostringtag">
```suggestion
      <emu-clause oldids="sec-sharedarraybuffer.prototype.toString" id="sec-sharedarraybuffer.prototype-@@tostringtag">
```

2024-02-19 20:38 UTC, ljharb commented on spec.html
> +      <emu-clause oldids="sec-sharedarraybuffer.prototype.toString" id="https://tc39.es/ecma262/#sec-sharedarraybuffer.prototype-@@tostringtag">
oh whoops :-p copy-paste. thanks

2024-02-19 20:39 UTC, linusg approved these changes
Thanks!

2024-02-20 01:48 UTC, michaelficarra approved these changes

2024-02-20 01:58 UTC, merged